### ISSUE TITLE
是否有快捷的方法获取userid？

### ISSUE THREAD

**Issue by XYZliang** [FupengWang/BigStudyHelper#1]
如题，想替全班没大学习的人直接大学习了，完成班上任务。抓包了一遍，不知道userid怎么出来的，也没有方法方便获取

**Comment by FupengWang** [comment]
这串userid应该是和一卡通账号密码挂钩的，有这串userid几乎可以畅通校内所有网站。目前获取的方法只有微信复制链接。（更麻烦点可以抓微信小程序智慧江财的包）

**Comment by XYZliang** [comment]
哎，我也是抓包出来的。userid应该是微信分配的，我们加入了江财的企业号，进入这个企业应用，微信生成的个人的识别码，学校服务器记录了每人的userid，然后返回个人信息。。。。。
在江财网上办事大厅用一卡通登陆后打开这个页面就可以无需userid进入，cookie是通用的。。
看来还是得收集这个链接。
