### ISSUE TITLE
openid文件要怎么填啊，是只需要填openid吗

### ISSUE THREAD

**Issue by lxp969** [FupengWang/BigStudyHelper#3]
是只需要填openid吗，然后我运行一直报错

**Comment by FupengWang** [comment]
一行一个openid, 例如 
![openid](https://user-images.githubusercontent.com/61930606/142444553-13d61446-c510-4202-ac70-0abfd28983ef.jpg)
不要留有空行

**Comment by lxp969** [comment]
好的，知道了，谢谢
